
    ##################################################
    ##  My Discord : https://discord.gg/dyccdcXMJn  ##
    ##################################################

welcome-message: true
welcome:
  msg: "&aBienvenue &f%player% &asur le Serveur !"
